spring:
 datasource:
   url: ${databaseUrl}
   username: ${usernameDB}
   password: ${passwordDB}
   hikari:
    connection-test-query: select 1
 sql:
   init:
    platform: postgres
 jpa:
  database: POSTGRESQL
  show-sql: true
  generate-ddl: true
  hibernate:
   ddl-auto: validate
 h2:
  console:
   enabled: true
 flyway:
#  locations:
#   - classpath:db/migration
  baseline-on-migrate: true
  validate-on-migrate: true

 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER 
